/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as AllTaskIdRouteImport } from './routes/all/$taskId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdPrsIndexRouteImport } from './routes/projects/$projectId/prs/index'
import { Route as AllPrsProjectIdIndexRouteImport } from './routes/all/prs/$projectId/index'
import { Route as ProjectsProjectIdTasksNewRouteImport } from './routes/projects/$projectId/tasks/new'
import { Route as ProjectsProjectIdTasksTaskIdRouteImport } from './routes/projects/$projectId/tasks/$taskId'
import { Route as ProjectsProjectIdPrsPrIdRouteImport } from './routes/projects/$projectId/prs/$prId'
import { Route as AllPrsProjectIdPrIdRouteImport } from './routes/all/prs/$projectId/$prId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AllTaskIdRoute = AllTaskIdRouteImport.update({
  id: '/all/$taskId',
  path: '/all/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPrsIndexRoute =
  ProjectsProjectIdPrsIndexRouteImport.update({
    id: '/prs/',
    path: '/prs/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AllPrsProjectIdIndexRoute = AllPrsProjectIdIndexRouteImport.update({
  id: '/all/prs/$projectId/',
  path: '/all/prs/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdTasksNewRoute =
  ProjectsProjectIdTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTasksTaskIdRoute =
  ProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPrsPrIdRoute =
  ProjectsProjectIdPrsPrIdRouteImport.update({
    id: '/prs/$prId',
    path: '/prs/$prId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AllPrsProjectIdPrIdRoute = AllPrsProjectIdPrIdRouteImport.update({
  id: '/all/prs/$projectId/$prId',
  path: '/all/prs/$projectId/$prId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all/$taskId': typeof AllTaskIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/all/prs/$projectId/$prId': typeof AllPrsProjectIdPrIdRoute
  '/projects/$projectId/prs/$prId': typeof ProjectsProjectIdPrsPrIdRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/tasks/new': typeof ProjectsProjectIdTasksNewRoute
  '/all/prs/$projectId/': typeof AllPrsProjectIdIndexRoute
  '/projects/$projectId/prs/': typeof ProjectsProjectIdPrsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all/$taskId': typeof AllTaskIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/all/prs/$projectId/$prId': typeof AllPrsProjectIdPrIdRoute
  '/projects/$projectId/prs/$prId': typeof ProjectsProjectIdPrsPrIdRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/tasks/new': typeof ProjectsProjectIdTasksNewRoute
  '/all/prs/$projectId': typeof AllPrsProjectIdIndexRoute
  '/projects/$projectId/prs': typeof ProjectsProjectIdPrsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all/$taskId': typeof AllTaskIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/all/prs/$projectId/$prId': typeof AllPrsProjectIdPrIdRoute
  '/projects/$projectId/prs/$prId': typeof ProjectsProjectIdPrsPrIdRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/tasks/new': typeof ProjectsProjectIdTasksNewRoute
  '/all/prs/$projectId/': typeof AllPrsProjectIdIndexRoute
  '/projects/$projectId/prs/': typeof ProjectsProjectIdPrsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all/$taskId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/'
    | '/all/prs/$projectId/$prId'
    | '/projects/$projectId/prs/$prId'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/tasks/new'
    | '/all/prs/$projectId/'
    | '/projects/$projectId/prs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all/$taskId'
    | '/projects/new'
    | '/projects/$projectId'
    | '/all/prs/$projectId/$prId'
    | '/projects/$projectId/prs/$prId'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/tasks/new'
    | '/all/prs/$projectId'
    | '/projects/$projectId/prs'
  id:
    | '__root__'
    | '/'
    | '/all/$taskId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/'
    | '/all/prs/$projectId/$prId'
    | '/projects/$projectId/prs/$prId'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/tasks/new'
    | '/all/prs/$projectId/'
    | '/projects/$projectId/prs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllTaskIdRoute: typeof AllTaskIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  AllPrsProjectIdPrIdRoute: typeof AllPrsProjectIdPrIdRoute
  AllPrsProjectIdIndexRoute: typeof AllPrsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all/$taskId': {
      id: '/all/$taskId'
      path: '/all/$taskId'
      fullPath: '/all/$taskId'
      preLoaderRoute: typeof AllTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/prs/': {
      id: '/projects/$projectId/prs/'
      path: '/prs'
      fullPath: '/projects/$projectId/prs/'
      preLoaderRoute: typeof ProjectsProjectIdPrsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/all/prs/$projectId/': {
      id: '/all/prs/$projectId/'
      path: '/all/prs/$projectId'
      fullPath: '/all/prs/$projectId/'
      preLoaderRoute: typeof AllPrsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/tasks/new': {
      id: '/projects/$projectId/tasks/new'
      path: '/tasks/new'
      fullPath: '/projects/$projectId/tasks/new'
      preLoaderRoute: typeof ProjectsProjectIdTasksNewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tasks/$taskId': {
      id: '/projects/$projectId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/prs/$prId': {
      id: '/projects/$projectId/prs/$prId'
      path: '/prs/$prId'
      fullPath: '/projects/$projectId/prs/$prId'
      preLoaderRoute: typeof ProjectsProjectIdPrsPrIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/all/prs/$projectId/$prId': {
      id: '/all/prs/$projectId/$prId'
      path: '/all/prs/$projectId/$prId'
      fullPath: '/all/prs/$projectId/$prId'
      preLoaderRoute: typeof AllPrsProjectIdPrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdPrsPrIdRoute: typeof ProjectsProjectIdPrsPrIdRoute
  ProjectsProjectIdTasksTaskIdRoute: typeof ProjectsProjectIdTasksTaskIdRoute
  ProjectsProjectIdTasksNewRoute: typeof ProjectsProjectIdTasksNewRoute
  ProjectsProjectIdPrsIndexRoute: typeof ProjectsProjectIdPrsIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdPrsPrIdRoute: ProjectsProjectIdPrsPrIdRoute,
  ProjectsProjectIdTasksTaskIdRoute: ProjectsProjectIdTasksTaskIdRoute,
  ProjectsProjectIdTasksNewRoute: ProjectsProjectIdTasksNewRoute,
  ProjectsProjectIdPrsIndexRoute: ProjectsProjectIdPrsIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllTaskIdRoute: AllTaskIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  AllPrsProjectIdPrIdRoute: AllPrsProjectIdPrIdRoute,
  AllPrsProjectIdIndexRoute: AllPrsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
